language: csharp
solution: Microservices.sln
mono: none

before_install:
- sudo apt-get install dotnet-sdk-2.1.300-preview2-008533

install:
- dotnet restore Microservices.sln

script:
- dotnet build Microservices.sln
- dotnet test AccountService/Accounts.Tests/Accounts.Tests.csproj