language: csharp
solution: Microservices.sln
mono: none
dotnet: latest

install:
- dotnet restore Microservices.sln

script:
- dotnet build Microservices.sln
- dotnet test AccountService/Accounts.Tests/Accounts.Tests.csproj