language: csharp
solution: Microservices.sln
mono: none
dotnet: 2.1.300
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

install:
- dotnet restore Microservices.sln

script:
- dotnet build Microservices.sln
- dotnet test ServiceCore/Core.Tests/Core.Tests.csproj /p:CollectCoverage=true
- dotnet test AccountService/Accounts.Tests/Accounts.Tests.csproj /p:CollectCoverage=true
- dotnet test MarkdownService/Markdown.Tests/Markdown.Tests.csproj /p:CollectCoverage=true