language: csharp
solution: Microservices.sln
mono: none
dotnet: 2.1.300

install:
- dotnet restore Microservices.sln

script:
- dotnet build Microservices.sln
- dotnet build ServiceCore/Core.Tests/Core.Tests.csproj
- dotnet test AccountService/Accounts.Tests/Accounts.Tests.csproj