language: csharp
solution: Microservices.sln
mono: none
dotnet: 2.1.300-preview1-008174

install:
- dotnet restore Microservices.sln

script:
- dotnet build Microservices.sln
- dotnet test AccountService/Accounts.Tests/Accounts.Tests.csproj