// <auto-generated />
using System;
using Markdown.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Markdown.Migrations
{
    [DbContext(typeof(MarkdownContext))]
    partial class MarkdownContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Markdown.Models.Document", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedAt");

                    b.Property<string>("Markdown");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
